apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort  # Ermöglicht externen Zugriff
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Port des Containers
